# Generated by Django 3.0.7 on 2020-10-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0007_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candiddidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image_upload')),
            ],
        ),
        migrations.CreateModel(
            name='Home_Job',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('job.job',),
        ),
    ]
