# Generated by Django 3.0.7 on 2020-10-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job',
        ),
    ]
