# Generated by Django 3.0.7 on 2020-10-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_company_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
