# Generated by Django 3.0.7 on 2020-10-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('job.job',),
        ),
    ]
