# Generated by Django 3.0.7 on 2020-10-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20201017_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
